//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StabilityApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StabilityApp.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I Drive.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string CognitivTest_down {
            get {
                return ResourceManager.GetString("CognitivTest_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CognitivTest_left {
            get {
                return ResourceManager.GetString("CognitivTest_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Test.
        /// </summary>
        public static string CognitivTest_name {
            get {
                return ResourceManager.GetString("CognitivTest_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CognitivTest_right {
            get {
                return ResourceManager.GetString("CognitivTest_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string CognitivTest_up {
            get {
                return ResourceManager.GetString("CognitivTest_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string MainPage_calibrate {
            get {
                return ResourceManager.GetString("MainPage_calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Test.
        /// </summary>
        public static string MainPage_cognitiveTest {
            get {
                return ResourceManager.GetString("MainPage_cognitiveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Test.
        /// </summary>
        public static string MainPage_mathTest {
            get {
                return ResourceManager.GetString("MainPage_mathTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Test.
        /// </summary>
        public static string MainPage_motionTest {
            get {
                return ResourceManager.GetString("MainPage_motionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string MainPage_name {
            get {
                return ResourceManager.GetString("MainPage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Mathproblem_continue {
            get {
                return ResourceManager.GetString("Mathproblem_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve the following equation.
        /// </summary>
        public static string Mathproblem_mathInfo {
            get {
                return ResourceManager.GetString("Mathproblem_mathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Test.
        /// </summary>
        public static string Mathproblem_name {
            get {
                return ResourceManager.GetString("Mathproblem_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Mathproblem_submit {
            get {
                return ResourceManager.GetString("Mathproblem_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string MotionTest_down {
            get {
                return ResourceManager.GetString("MotionTest_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string MotionTest_left {
            get {
                return ResourceManager.GetString("MotionTest_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string MotionTest_up {
            get {
                return ResourceManager.GetString("MotionTest_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string MotiontTest_right {
            get {
                return ResourceManager.GetString("MotiontTest_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Result_main {
            get {
                return ResourceManager.GetString("Result_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, you are to tired/drunk to drive.
        /// </summary>
        public static string ResultPage_false {
            get {
                return ResourceManager.GetString("ResultPage_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultPage_name {
            get {
                return ResourceManager.GetString("ResultPage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations you are capable of driving.
        /// </summary>
        public static string ResultPage_true {
            get {
                return ResourceManager.GetString("ResultPage_true", resourceCulture);
            }
        }
    }
}
